name: TicketPlugin
version: 0.01
main: io.github.plizga.ticketplugin.TicketPlugin
authors: [Plizga]
description: A Ticket Plugin for Spigot that allows users to submit tickets, and allows moderators to answer said tickets.
website: plizga.github.io
softdepend: [Tythan]
commands:
  request:
    description: Allows a player to create a new ticket.
    usage: /<command>

permissions:
  ticketplugin.create:
    default: true
    description: create a new request ticket for the staff to answer.
  ticketplugin.view:
    default: true
    description: allows a player to view their currently open tickets.
  ticketplugin.cancel:
    default: true
    description: allows a player to cancel 1 or all of their tickets.


