name: TicketPlugin
version: 0.01
main: io.github.plizga.ticketplugin.TicketPlugin
authors: [Plizga]
description: A Ticket Plugin for Spigot that allows users to submit tickets, and allows moderators to answer said tickets.
website: plizga.github.io
softdepend: [Tythan]
commands:
  ticket:
    description: Allows a player to create a new ticket.
    usage: /<command>


permissions:
  ticket.finalize:
    default: false
    description: internal command that processes and finalizes tickets.